name: 'Build Debian package: Buster'
description: 'Build a Debian package, using the latest version of Debian Buster'
inputs:
  architecture:
    description: 'Architecture of the Debian Package (Multi-Arch)'
    required: false
    default: 'amd64'

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.architecture }}

branding:
  icon: package
  color: gray-dark
